level2/ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path
from apptwo import views
from django.conf.urls import url, include

urlpatterns = [
    url(r'^$', views.base, name = 'base'),
    path('admin/', admin.site.urls),
    url(r'^apptwo/', include('apptwo.urls')),
    url(r'^logout/$', views.user_logout, name = 'logout'),


]

level2/ProTwo/apptwo/urls.py
from django.conf.urls import url
from apptwo import views
from django.contrib import admin
from django.urls import path


app_name = 'apptwo'


urlpatterns = [
   url(r'^test/$', views.test, name = 'test' ),
   url(r'^$', views.base, name = 'base' ),
   url(r'^test2/$', views.test2, name = 'test2' ),
   url(r'^test3/$', views.test3, name = 'test3' ),
   url(r'^register/$', views.register, name = 'register' ),
   url(r'^index2/$', views.index2, name = 'index2' ),
   # url(r'^admin/$', admin.site.urls),
   path('admin/', admin.site.urls),

   url(r'special/', views.special, name = 'special'),
   url(r'^login/$', views.user_login, name = 'login'),

]

level2/ProTwo/apptwo/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

# class User(models.Model):
#     first_name = models.CharField(max_length = 128)
#     last_name = models.CharField(max_length = 128)
#     email = models.EmailField(max_length = 264, unique = True)


#this class adds additional information to user extending class features

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = 'True')

    def __str__(self):
        return self.user.username

# class UserForm(forms.ModelForm):
#     password = forms.CharField(widget = forms.PasswordInput())
#
#     class Meta():
#         model = User
#         fields = ('username', 'email', 'password')
#

level2/ProTwo/apptwo/forms.py
from django import forms
from django.contrib.auth.models import User
from apptwo.models import UserProfileInfo


class NewUserForm(forms.ModelForm):
    #password = forms.CharField(widget = forms.passwordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

level2/ProTwo/apptwo/views.py
from django.shortcuts import render
from apptwo.models import User
# Create your views here.
from apptwo.forms import NewUserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required




def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'apptwo/index.html', context_dict)

# def users(request):
#     user_list = User.objects.order_by('first_name')
#     user_dict = {'users' : user_list}
#     return render(request, 'apptwo/users.html', context = user_dict)

def users(request):
    form = NewUserForm()
    if request.method == 'POST':
        form = NewUserForm(request.POST)

    if form.is_valid():
        form.save(commit = True)
        return index(request)
    else:
        print('error form invalid')

    return render(request, 'apptwo/users.html', {'form': form})


def test(request):
    return render(request, 'apptwo/test.html')

def index2(request):
    return render(request, 'apptwo/index2.html')


def base(request):
    return render(request, 'apptwo/base.html')





def test2(request):
    return render(request, 'apptwo/test2.html')


def test3(request):
    return render(request, 'apptwo/test3.html')


def register(request):
    registered = False
    if request.method == "POST":
        user_form = NewUserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit = False)
            profile.user = user
            if 'profile_pics' in request.FILES:
                profile.profile_pic = request.FILES['profile_pics']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form  = NewUserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'apptwo/registration.html',
    {'user_form': user_form, 'profile_form': profile_form, 'registered':registered }
    )

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE ")
        else:
            print('some one tried to login and failed')
            return HttpResponse('invalid login details supplied')
    else:
        return render(request, 'apptwo/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('base'))


@login_required
def special(request):
    return HttpResponse("You are logged in nice")

level2/ProTwo/templates/apptwo/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title></title>
  </head>
  <body>

    <nav class = 'navbar navbar-default navbar-static-top'>
      <div class="container">

        <div class="jumbotron">

          <ul class = 'nav navbar-nav'>
           <li><a class = 'navbar-brand' href="{% url 'base' %}">HOME</a></li>
            <li><a class = "navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
           <li><a class = "navbar-link" href="{% url 'apptwo:register' %}">Registration</a></li>
           {% if user.is_authenticated %}
           <li><a class = 'navbar-link' href="{% url 'logout' %}">LogOut</a></li>
            {% else %}
            <li><a class = "navbar-link" href="{% url 'apptwo:login' %}">Login</a></li>
            {% endif %}



           <h1>welcome to django final level</h1>


          </ul>


        </div>

      </div>

    </nav>

    <div class="container">

     {% block body_block %}
     {% endblock %}

    </div>

  </body>
</html>

level2/ProTwo/templates/apptwo/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  </head>
  <body>
   <nav class = 'navbar navbar-default navbar-static-top'>
     <div class="container">
       <ul class = 'nav navbar-nav'>
         <li ><a class ="navbar-brand" href="{% url 'apptwo:test' %}">BRAND</a></li>
         <li><a class = "navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
         <li><a class = "navbar-link" href="{% url 'apptwo:users' %}">SignUp</a></li>

       </ul>

     </div>

   </nav>

   <div class="container">
     {% block body_block %}
     <h1>Hello baby</h1>
        {{ text | cut:'o' }}<p></p>
        {{ number|add:"99" }}
     {% endblock %}
   </div>
  </body>
</html>

level2/ProTwo/templates/apptwo/index2.html
{% extends "apptwo/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>

</div>

{% endblock %}

level2/ProTwo/templates/apptwo/login.html
{% extends 'apptwo/base.html' %}
{% block body_block %}


<div class="jumbotron">
  <h1>please login</h1>
   <form action="{% url 'apptwo:login' %}" method="post">

     {% csrf_token %}
     <label for="username">username</label>
     <input type="text" name="username" placeholder = "enter username">

     <label for=password">Password</label>
     <input type="password" name="password" value="">
     <input type="submit" name="" value="Login">
        </form>
 </div>

{% endblock %}

level2/ProTwo/templates/apptwo/registration.html
{% extends "apptwo/base.html" %}

{% load static %}

{% block body_block %}

<div class="jumbotron">
{% if registered %}
<h1>ThankYou for Registering </h1>

{% else %}
<h1>Register here!</h1>
<h3>fill out the form: </h3>

<form method ='post' enctype ='multipart/form-data'>
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <input type="submit" name="" value="Register">
</form>

{% endif %}

</div>
{% endblock %}

level2/ProTwo/templates/apptwo/test.html
<!DOCTYPE html>


{% extends "apptwo/index.html" %}
{% block body_block %}
  <h1>Best Brand Ever</h1>
  <h1>this is test.html page showing</h1>
{% endblock %}

level2/ProTwo/templates/apptwo/test2.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome to test2 page</h1>
        <a href="{% url 'admin:index' %}">click here to go to admin page</a><p></p>
        <a href="{% url 'apptwo:test' %}">click here to go to test page</a><p></p>
        <a href="{% url 'apptwo:users' %}">click here to go to users page</a><p></p>
        <a href="{% url 'index' %}">click here to go to index page</a><p></p>
        </body>
      </div>
    </div>


</html>

level2/ProTwo/templates/apptwo/test3.html
<!DOCTYPE html>


{% extends "apptwo/index.html" %}
{% block body_block %}
  <h1>WELcome to index</h1>
  <h1>this is test3.html page showing</h1>
{% endblock %}

level2/ProTwo/templates/apptwo/users.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
  <div class="container">
    <div class="jumbotron">
      <h1>Please sign in here</h1>
      <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" class = 'btn btn-primary' value="Submit">

      </form>
  </div>
  </div>


















    <!-- <h1>here are your users for apptwo</h1>
    {% if users %}

    <ol>
      {% for person in users %}
      <li>User Info</li>
      <ul>
        <li>First name : {{ person.first_name }}</li>
        <li>Last Name: {{ person.last_name }}</li>
        <li>email id : {{ person.email}}</li>
      </ul>

      {% endfor %}
    </ol>

    {% endif %} -->

  </body>
</html>